### ISSUE TITLE
Module not found: Error: Cannot resolve module 'net' in /../../node_modules/ip-range-generator

### ISSUE THREAD

**Issue by khatekar** [ezpaarse-project/ip-range-generator#1]
There isn't a 'net' package added. It's complaining for 'module not found'

**Comment by nojhamster** [comment]
There are no external dependencies, `net` is a built-in module in node. Are you using a module bundler like `webpack` or `browserify` ? Webpack requires [some configuration](http://webpack.github.io/docs/configuration.html#node) in order to work with node modules.

**Comment by khatekar** [comment]
Yes, I am using a module bundler 'webpack'.
It is still complaining about 
Module not found: Error: Cannot resolve module 'net' in /uesr_dir/my_product_dir/node_modules/ip-range-generator

**Comment by nojhamster** [comment]
Actually webpack doesn't have any polyfill for the net module. I changed for a regex-based validation of IPs, now it should bundle flawlessly :)

**Comment by khatekar** [comment]
Great! 
Thanks. I will re-install it.
